version: '3.4'

services:
  restrictionsservice:
    image: restrictionsservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
