version: '3.4'

services:
  restrictionsservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      GOOGLE_APPLICATION_CREDENTIALS: /app/serviceAccountKey.json 
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
