version: '3.4'

services:
  restrictionsservice:
    image: restrictionsservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: firebase